create table "public"."Projects" (
  "id"           bigint                   generated by default as identity not null,
  "created_at"   timestamp with time zone not null default now(),
  "created_by"   bigint,
  "name"         character varying        not null default ''::character varying,
  "description"  text                     not null default ''::text,
  "completed_at" timestamp with time zone,
  "public"       boolean                  not null default true,
  constraint "Projects_name_key" unique (name),
  constraint "Projects_pkey" primary key (id),
  constraint "Projects_created_by_fkey" foreign key (created_by) references public."Users"(id) on update cascade on delete set null
);

alter table "public"."Projects"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Projects" to "anon", "authenticated", "postgres", "service_role";
