create table "public"."Schematics" (
  "id"        bigint            generated by default as identity not null,
  "name"      character varying default ''::character varying,
  "file_path" character varying not null default ''::character varying,
  constraint "Schematics_name_key" unique (name),
  constraint "Schematics_pkey" primary key (id)
);

alter table "public"."Schematics"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Schematics" to "anon", "authenticated", "postgres", "service_role";
