create table "public"."Users" (
  "id"                 bigint                   generated by default as identity not null,
  "created_at"         timestamp with time zone not null default now(),
  "authenticated_user" uuid,
  "username"           character varying        not null default ''::character varying,
  constraint "Users_authenticated_users_fkey" foreign key (authenticated_user) references auth.users(id),
  constraint "Users_pkey" primary key (id),
  constraint "Users_username_key" unique (username)
);

alter table "public"."Users"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Users" to "anon", "authenticated", "postgres", "service_role";
