set local check_function_bodies = off;

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "service_role";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "service_role";

create table "public"."Builds" (
  "created_at" timestamp with time zone not null default now(),
  "project"    bigint                   not null,
  "schematic"  bigint                   not null,
  "coord_x"    real,
  "coord_y"    real,
  "coord_z"    real,
  constraint "Builds_pkey" primary key (project, schematic)
);

alter table "public"."Builds"
  enable row level security;

create table "public"."Contributions" (
  "created_at" timestamp with time zone not null default now(),
  "project"    bigint                   not null,
  "user"       bigint                   not null,
  constraint "Contributions_pkey" primary key (project, "user")
);

alter table "public"."Contributions"
  enable row level security;

create table "public"."Dependencies" (
  "project_id"    bigint not null,
  "depends_on_id" bigint not null,
  constraint "Can't depend on itself" check ((project_id <> depends_on_id)),
  constraint "Dependencies_pkey" primary key (project_id, depends_on_id)
);

alter table "public"."Dependencies"
  enable row level security;

create table "public"."Projects" (
  "id"           bigint                   generated by default as identity not null,
  "created_at"   timestamp with time zone not null default now(),
  "created_by"   bigint,
  "name"         character varying        not null default ''::character varying,
  "description"  text                     not null default ''::text,
  "completed_at" timestamp with time zone,
  "public"       boolean                  not null default true,
  constraint "Projects_name_key" unique (name),
  constraint "Projects_pkey" primary key (id)
);

alter table "public"."Projects"
  enable row level security;

create table "public"."Schematics" (
  "id"        bigint            generated by default as identity not null,
  "name"      character varying default ''::character varying,
  "file_path" character varying not null default ''::character varying,
  constraint "Schematics_name_key" unique (name),
  constraint "Schematics_pkey" primary key (id)
);

alter table "public"."Schematics"
  enable row level security;

create table "public"."Users" (
  "id"                 bigint                   generated by default as identity not null,
  "created_at"         timestamp with time zone not null default now(),
  "authenticated_user" uuid,
  "username"           character varying        not null default ''::character varying,
  constraint "Users_pkey" primary key (id),
  constraint "Users_username_key" unique (username)
);

alter table "public"."Users"
  enable row level security;

create or replace function public.auto_add_owner_as_contributor()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
begin
  insert into public."Contributions" (project, "user")
  values (NEW.id, NEW.created_by);
  return NEW;
end;
$function$;

alter table "public"."Builds"
  add constraint "Builds_project_fkey" foreign key (project) references public."Projects"(id) on update cascade on delete cascade;

alter table "public"."Contributions"
  add constraint "Contributions_project_fkey" foreign key (project) references public."Projects"(id) on update cascade on delete cascade;

alter table "public"."Dependencies"
  add constraint "Dependencies_depends_on_id_fkey" foreign key (depends_on_id) references public."Projects"(id) on update cascade on delete cascade;

alter table "public"."Dependencies"
  add constraint "Dependencies_project_id_fkey" foreign key (project_id) references public."Projects"(id) on update cascade on delete cascade;

alter table "public"."Builds"
  add constraint "Builds_schematic_fkey" foreign key (schematic) references public."Schematics"(id) on update cascade on delete cascade;

alter table "public"."Users"
  add constraint "Users_authenticated_users_fkey" foreign key (authenticated_user) references auth.users(id);

alter table "public"."Contributions"
  add constraint "Contributions_user_fkey" foreign key ("user") references public."Users"(id) on update cascade on delete cascade;

alter table "public"."Projects"
  add constraint "Projects_created_by_fkey" foreign key (created_by) references public."Users"(id) on update cascade on delete set null;

create index idx_users_authenticated_user on public."Users" using btree (authenticated_user);

create trigger trg_auto_contributor
  after insert on public."Projects"
  for each row
  execute function public.auto_add_owner_as_contributor();

create policy "anon_select_public_builds" on "public"."Builds"
  for select
  to "anon"
  using ((exists ( select 1
   from public."Projects" p
  where ((p.id = "Builds".project) AND (p.public = true)))));

create policy "authenticated_select_all_builds" on "public"."Builds"
  for select
  to "authenticated"
  using (true);

create policy "contributor_delete_builds" on "public"."Builds"
  for delete
  to "authenticated"
  using ((exists ( select 1
   from (public."Contributions" c
     JOIN public."Users" u on ((u.id = c."user")))
  where ((c.project = "Builds".project) AND (u.authenticated_user = ( select auth.uid() as uid))))));

create policy "contributor_insert_builds" on "public"."Builds"
  for insert
  to "authenticated"
  with check ((EXISTS ( SELECT 1
   FROM (public."Contributions" c
     JOIN public."Users" u ON ((u.id = c."user")))
  WHERE ((c.project = "Builds".project) AND (u.authenticated_user = ( SELECT auth.uid() AS uid))))));

create policy "contributor_update_builds" on "public"."Builds"
  for update
  to "authenticated"
  using ((exists ( select 1
   from (public."Contributions" c
     JOIN public."Users" u on ((u.id = c."user")))
  where ((c.project = "Builds".project) AND (u.authenticated_user = ( select auth.uid() as uid))))))
  with check ((EXISTS ( SELECT 1
   FROM (public."Contributions" c
     JOIN public."Users" u ON ((u.id = c."user")))
  WHERE ((c.project = "Builds".project) AND (u.authenticated_user = ( SELECT auth.uid() AS uid))))));

create policy "anon_select_public_contributions" on "public"."Contributions"
  for select
  to "anon"
  using ((exists ( select 1
   from public."Projects" p
  where ((p.id = "Contributions".project) AND (p.public = true)))));

create policy "authenticated_select_all_contributions" on "public"."Contributions"
  for select
  to "authenticated"
  using (true);

create policy "contributor_delete_contributions" on "public"."Contributions"
  for delete
  to "authenticated"
  using ((exists ( select 1
   from (public."Contributions" c
     JOIN public."Users" u on ((u.id = c."user")))
  where ((c.project = "Contributions".project) AND (u.authenticated_user = ( select auth.uid() as uid))))));

create policy "contributor_insert_contributions" on "public"."Contributions"
  for insert
  to "authenticated"
  with check ((EXISTS ( SELECT 1
   FROM (public."Contributions" c
     JOIN public."Users" u ON ((u.id = c."user")))
  WHERE ((c.project = "Contributions".project) AND (u.authenticated_user = ( SELECT auth.uid() AS uid))))));

create policy "anon_select_public_dependencies" on "public"."Dependencies"
  for select
  to "anon"
  using ((exists ( select 1
   from public."Projects" p
  where ((p.id = "Dependencies".project_id) AND (p.public = true)))));

create policy "authenticated_select_all_dependencies" on "public"."Dependencies"
  for select
  to "authenticated"
  using (true);

create policy "contributor_delete_dependencies" on "public"."Dependencies"
  for delete
  to "authenticated"
  using ((exists ( select 1
   from (public."Contributions" c
     JOIN public."Users" u on ((u.id = c."user")))
  where ((c.project = "Dependencies".project_id) AND (u.authenticated_user = ( select auth.uid() as uid))))));

create policy "contributor_insert_dependencies" on "public"."Dependencies"
  for insert
  to "authenticated"
  with check ((EXISTS ( SELECT 1
   FROM (public."Contributions" c
     JOIN public."Users" u ON ((u.id = c."user")))
  WHERE ((c.project = "Dependencies".project_id) AND (u.authenticated_user = ( SELECT auth.uid() AS uid))))));

create policy "contributor_update_dependencies" on "public"."Dependencies"
  for update
  to "authenticated"
  using ((exists ( select 1
   from (public."Contributions" c
     JOIN public."Users" u on ((u.id = c."user")))
  where ((c.project = "Dependencies".project_id) AND (u.authenticated_user = ( select auth.uid() as uid))))))
  with check ((EXISTS ( SELECT 1
   FROM (public."Contributions" c
     JOIN public."Users" u ON ((u.id = c."user")))
  WHERE ((c.project = "Dependencies".project_id) AND (u.authenticated_user = ( SELECT auth.uid() AS uid))))));

create policy "anon_select_public_projects" on "public"."Projects"
  for select
  to "anon"
  using ((public = true));

create policy "authenticated_insert_projects" on "public"."Projects"
  for insert
  to "authenticated"
  with check (true);

create policy "authenticated_select_all_projects" on "public"."Projects"
  for select
  to "authenticated"
  using (true);

create policy "contributor_update_projects" on "public"."Projects"
  for update
  to "authenticated"
  using ((exists ( select 1
   from (public."Contributions" c
     JOIN public."Users" u on ((u.id = c."user")))
  where ((c.project = "Projects".id) AND (u.authenticated_user = ( select auth.uid() as uid))))))
  with check ((EXISTS ( SELECT 1
   FROM (public."Contributions" c
     JOIN public."Users" u ON ((u.id = c."user")))
  WHERE ((c.project = "Projects".id) AND (u.authenticated_user = ( SELECT auth.uid() AS uid))))));

create policy "owner_delete_projects" on "public"."Projects"
  for delete
  to "authenticated"
  using ((exists ( select 1
   from public."Users" u
  where ((u.id = "Projects".created_by) AND (u.authenticated_user = ( select auth.uid() as uid))))));

create policy "anon_select_public_schematics" on "public"."Schematics"
  for select
  to "anon"
  using ((exists ( select 1
   from (public."Builds" b
     JOIN public."Projects" p on ((p.id = b.project)))
  where ((b.schematic = "Schematics".id) AND (p.public = true)))));

create policy "authenticated_insert_schematics" on "public"."Schematics"
  for insert
  to "authenticated"
  with check (true);

create policy "authenticated_select_all_schematics" on "public"."Schematics"
  for select
  to "authenticated"
  using (true);

create policy "contributor_delete_schematics" on "public"."Schematics"
  for delete
  to "authenticated"
  using ((exists ( select 1
   from ((public."Builds" b
     JOIN public."Contributions" c on ((c.project = b.project)))
     JOIN public."Users" u on ((u.id = c."user")))
  where ((b.schematic = "Schematics".id) AND (u.authenticated_user = ( select auth.uid() as uid))))));

create policy "contributor_update_schematics" on "public"."Schematics"
  for update
  to "authenticated"
  using ((exists ( select 1
   from ((public."Builds" b
     JOIN public."Contributions" c on ((c.project = b.project)))
     JOIN public."Users" u on ((u.id = c."user")))
  where ((b.schematic = "Schematics".id) AND (u.authenticated_user = ( select auth.uid() as uid))))))
  with check ((EXISTS ( SELECT 1
   FROM ((public."Builds" b
     JOIN public."Contributions" c ON ((c.project = b.project)))
     JOIN public."Users" u ON ((u.id = c."user")))
  WHERE ((b.schematic = "Schematics".id) AND (u.authenticated_user = ( SELECT auth.uid() AS uid))))));

create policy "anyone_select_users" on "public"."Users"
  for select
  to "anon", "authenticated"
  using (true);

create policy "own_profile_update" on "public"."Users"
  for update
  to "authenticated"
  using ((authenticated_user = ( select auth.uid() as uid)))
  with check ((authenticated_user = ( SELECT auth.uid() AS uid)));

comment on table "public"."Builds" is 'Schematics used in projects';

comment on table "public"."Contributions" is 'Users who have engaged in a project';

comment on table "public"."Dependencies" is 'Project dependencies';

revoke all on function "public"."auto_add_owner_as_contributor"() from public;

grant execute on function "public"."auto_add_owner_as_contributor"() to "postgres";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Builds" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Contributions" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Dependencies" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Projects" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Schematics" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Users" to "anon", "authenticated", "postgres", "service_role";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "anon";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "authenticated";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "service_role";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "anon";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "authenticated";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "service_role";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "anon";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "authenticated";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "service_role";
